apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sheri1/pp-app-backend:latest 
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"



