apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use NLB (Network Load Balancer) for low latency, or "alb" for Application Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: frontend  # Match this to the label selector of your frontend deployment
  ports:
    - protocol: TCP
      port: 80  # The external port exposed by the load balancer
      targetPort: 80  # The port your React app is running on inside the pod (usually 80 or 3000)
