apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer   # Confirm this is correctly set
  ports:
    - port: 80         # Port defined in values.yaml
      targetPort: 80
  selector:
    app: frontend
